name: dtwdistance
description: Flutter Package for time series distances (e.g. Dynamic Time Warping) used in the DTAI Research Group.. (https://en.wikipedia.org/wiki/Dynamic_time_warping)
version: 1.0.0
author:
  - Sattyam Jain<sattyamjain96@gmail.com>
  - ugo chirico ugo.chirico@cyberneid.com

homepage: https://github.com/sattyamjjain/dtwdistance.git


environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
