name: dtwdistance
description: Flutter Package to find the distance between two signals.
version: 0.0.1
author: Sattyam Jain<sattyamjain96@gmail.com>
homepage: https://github.com/sattyamjjain/dtwdistance.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 1.0.0
  quiver: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
